module.exports = {
  STORE_KEY: 'a56z0fzrNpl^2',
  BASE_URL: 'http://139.59.76.223/monotech/webservice/',
  Signin :'Signin',
  Signup :'Signup',
  front_main :'front_main',
  industry :'',
  data:[],
  category_name:'',
  industry_name:'',
  category : '',
   productid :'',
   profile :'',
   name :'',
   isScreen :'0',
   email :'',
   mobile :'',
   catname:'',
   share_url:'',
   share_product_name:'',
   rating_product : 'rating_product',
   product_review_list:'product_review_list',
   get_all_brands:'get_all_brands',
   product_description:'product_description',
   submit_feedback:'submit_feedback',
   monotech_data:'monotech_data',
   forget_password : 'forget_password',
   otp_for_forget:'otp_for_forget',
   otps:'',
   _token:'',
   model_product_name:'',
   forget_password_by_mobile:'forget_password_by_mobile',
   get_all_alliances:'get_all_alliances',
   update_profile_patient : 'update_profile_patient',
  derive_detail_industry :'derive_detail_industry',
  fmobile:'',
  derive_detail_category : 'derive_detail_category',
  info_number :'',
  userid :'',
  myreview :[],
  rating :'3',
  info_email : '',
  add_bookmark :'add_bookmark',
  list_bookmark: 'list_bookmark',
  mainid : '',
  dervie_detail_of_product : 'dervie_detail_of_product',
  submit_enquiry :'submit_enquiry',
  need_help:'need_help',
  list_enquiry :'list_enquiry',
  submit_consumable_request :'submit_consumable_request',


userInfo :[],
myname :'',
mymobile :'',
myemail :'',
mymobile :'',
mypassword :'',
mydeviceID :'',
mydeviceType :'',
mydeviceToken :'',
mymodel_name :'',
mycarrier_name :'',
mydevice_country :'',
mydevice_memory :'',



//     name: this.state.username,
//     mobile: this.state.mobile,
//     email: this.state.email,
//     password: this.state.password,
//     deviceID: DeviceInfo.getUniqueID(),
//     deviceType: Platform.OS,
//     deviceToken: '',
//     model_name: DeviceInfo.getModel(),
//     carrier_name: DeviceInfo.getCarrier(),
//     device_country: DeviceInfo.getDeviceCountry(),
//     device_memory: DeviceInfo.getTotalMemory(),
//     has_notch: DeviceInfo.hasNotch(),
//     manufacture: DeviceInfo.getManufacturer(),
//     ip_address: this.state.iPAddress,

category :[],
product :[],
model :[],
description :[],

  COLOR: {
    ORANGE: '#C50',
    DARKBLUE: '#0F3274',
    LIGHTBLUE: '#6EA8DA',
    DARKGRAY: '#999',
  },
};
